"""Add offer_sent_at to Candidate model

Revision ID: 0e064af42b1c
Revises: fe1c9a5e8ed0
Create Date: 2025-05-22 10:12:57.341633 # Ή η δική σου Create Date

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e064af42b1c'
down_revision = 'fe1c9a5e8ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_candidates_offer_sent_at'), ['offer_sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_offer_sent_at'))
        batch_op.drop_column('offer_sent_at')
    # ### end Alembic commands ###