"""Ensure offer acceptance token fields for Candidate

Revision ID: 289bddbf66e9
Revises: 5cc7d1f3c3ff
Create Date: 2025-05-20 21:00:50.196829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289bddbf66e9'
down_revision = '5cc7d1f3c3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_acceptance_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('offer_acceptance_token_expiration', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_candidates_offer_acceptance_token'), ['offer_acceptance_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_offer_acceptance_token'))
        batch_op.drop_column('offer_acceptance_token_expiration')
        batch_op.drop_column('offer_acceptance_token')

    # ### end Alembic commands ###
