"""Initial database schema with all current models including Interview

Revision ID: 3b83f418a79b
Revises: 
Create Date: 2025-05-17 13:36:33.570905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b83f418a79b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidates',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('education_summary', sa.Text(), nullable=True),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('skills_summary', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('seminars', sa.Text(), nullable=True),
    sa.Column('cv_original_filename', sa.String(length=255), nullable=True),
    sa.Column('cv_storage_path', sa.String(length=512), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_location', sa.String(length=255), nullable=True),
    sa.Column('interview_type', sa.String(length=100), nullable=True),
    sa.Column('interviewers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('offers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_rating', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('hr_comments', sa.Text(), nullable=True),
    sa.Column('confirmation_uuid', sa.UUID(), nullable=False),
    sa.Column('candidate_confirmation_status', sa.String(length=20), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('confirmation_uuid'),
    sa.UniqueConstraint('email', 'company_id', name='uq_candidates_email_company_id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_submission_date'), ['submission_date'], unique=False)

    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('rejection_email_template', sa.Text(), nullable=True),
    sa.Column('interview_invitation_email_template', sa.Text(), nullable=True),
    sa.Column('default_interview_reminder_timing_minutes', sa.Integer(), nullable=True),
    sa.Column('enable_reminders_feature_for_company', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('position_id'),
    sa.UniqueConstraint('position_name', 'company_id', name='uq_position_name_company_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enable_email_interview_reminders', sa.Boolean(), nullable=True),
    sa.Column('interview_reminder_lead_time_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('candidate_position_association',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'position_id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('proposed_slot_1_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_slot_1_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_slot_2_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_slot_2_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_slot_3_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_slot_3_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('interview_type', sa.String(length=50), nullable=True),
    sa.Column('notes_for_candidate', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason_candidate', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'SCHEDULED', 'COMPLETED', 'CANDIDATE_REJECTED_ALL', 'CANCELLED_BY_RECRUITER', 'CANCELLED_BY_CANDIDATE', 'EXPIRED', name='interviewstatus'), nullable=False),
    sa.Column('confirmation_token', sa.String(length=36), nullable=True),
    sa.Column('token_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_confirmation_token'), ['confirmation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_interviews_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_status'))
        batch_op.drop_index(batch_op.f('ix_interviews_confirmation_token'))

    op.drop_table('interviews')
    op.drop_table('candidate_position_association')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('positions')
    op.drop_table('company_settings')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_submission_date'))
        batch_op.drop_index(batch_op.f('ix_candidates_email'))
        batch_op.drop_index(batch_op.f('ix_candidates_current_status'))

    op.drop_table('candidates')
    op.drop_table('companies')
    # ### end Alembic commands ###
