"""Add owner_user_id to Company, update User and Interview models with new fields and constraits

Revision ID: 4386126e1f3e
Revises: 3b83f418a79b
Create Date: 2025-05-17 18:36:02.278770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4386126e1f3e'
down_revision = '3b83f418a79b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['owner_user_id'], ['id'])

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_scheduled_start_time'), ['scheduled_start_time'], unique=False)
        batch_op.drop_constraint('interviews_recruiter_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['recruiter_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('enable_email_interview_reminders',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('interview_reminder_lead_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('users_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_company_id_fkey', 'companies', ['company_id'], ['id'])
        batch_op.alter_column('interview_reminder_lead_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('enable_email_interview_reminders',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('confirmed_on')

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('interviews_recruiter_id_fkey', 'users', ['recruiter_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_interviews_scheduled_start_time'))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###
