"""Update candidate confirmation status lenght, interview tokens and reqruiter_id nullable

Revision ID: 5cc7d1f3c3ff
Revises: c5887690bcdb
Create Date: 2025-05-19 13:32:07.295017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc7d1f3c3ff'
down_revision = 'c5887690bcdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_last_changed_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('candidate_confirmation_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('cancellation_token_expiration', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('confirmation_token',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_interviews_cancellation_token'), ['cancellation_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_cancellation_token'))
        batch_op.alter_column('confirmation_token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('recruiter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('cancellation_token_expiration')
        batch_op.drop_column('cancellation_token')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('candidate_confirmation_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('status_last_changed_date')

    # ### end Alembic commands ###
