"""Add candidate confirmation status and uuid to Candidate model

Revision ID: 819888491b73
Revises: faa87c33089e
Create Date: 2025-05-12 11:36:27.088581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819888491b73'
down_revision = 'faa87c33089e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_confirmation_status', sa.String(length=50), nullable=True, comment="Status of candidate's confirmation for the scheduled interview (Pending, Confirmed, Declined)"))
        batch_op.add_column(sa.Column('confirmation_uuid', sa.String(length=36), nullable=True, comment='Unique identifier for interview confirmation links sent to candidate'))
        batch_op.create_index(batch_op.f('ix_candidates_candidate_confirmation_status'), ['candidate_confirmation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_confirmation_uuid'), ['confirmation_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_confirmation_uuid'))
        batch_op.drop_index(batch_op.f('ix_candidates_candidate_confirmation_status'))
        batch_op.drop_column('confirmation_uuid')
        batch_op.drop_column('candidate_confirmation_status')

    # ### end Alembic commands ###
