"""align_models_company_settings_pk

Revision ID: 8732c949d722
Revises: b47521eb728c
Create Date: 2025-05-14 18:55:43.846477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8732c949d722'
down_revision = 'b47521eb728c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index('ix_candidates_candidate_confirmation_status')
        batch_op.drop_index('ix_candidates_company_id')
        batch_op.drop_constraint('uq_candidates_cv_storage_path', type_='unique')
        batch_op.drop_constraint('fk_candidates_company_id_companies', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_companies_name')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('fk_companies_owner_user_id_users', type_='foreignkey')
        batch_op.drop_column('owner_user_id')

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('ix_positions_company_id')
        batch_op.drop_index('ix_positions_position_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('ix_positions_position_name', ['position_name'], unique=False)
        batch_op.create_index('ix_positions_company_id', ['company_id'], unique=False)

    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_companies_owner_user_id_users', 'users', ['owner_user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_companies_name', ['name'], unique=True)

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_candidates_company_id_companies', 'companies', ['company_id'], ['id'])
        batch_op.create_unique_constraint('uq_candidates_cv_storage_path', ['cv_storage_path'])
        batch_op.create_index('ix_candidates_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_candidates_candidate_confirmation_status', ['candidate_confirmation_status'], unique=False)

    # ### end Alembic commands ###
