"""add_cv_pdf_fields_to_candidate

Revision ID: d4affb3bc651
Revises: da429559eba5
Create Date: 2025-05-22 18:01:16.801249

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4affb3bc651'
down_revision = 'da429559eba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ΑΦΑΙΡΕΣΕ Ή ΚΑΝΕ COMMENT OUT ΤΟ ΠΑΡΑΚΑΤΩ ΜΠΛΟΚ ΕΠΕΙΔΗ ΤΟ CONSTRAINT ΥΠΑΡΧΕΙ ΗΔΗ
    # with op.batch_alter_table('candidate_branch_association', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_candidate_branch', ['candidate_id', 'branch_id'])

    # ΚΡΑΤΑΜΕ ΑΥΤΟ ΤΟ ΜΠΛΟΚ ΓΙΑ ΤΗΝ ΠΡΟΣΘΗΚΗ ΤΩΝ ΝΕΩΝ ΠΕΔΙΩΝ
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cv_pdf_storage_key', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ΚΡΑΤΑΜΕ ΑΥΤΟ ΤΟ ΜΠΛΟΚ ΓΙΑ ΤΗ ΔΙΑΓΡΑΦΗ ΤΩΝ ΝΕΩΝ ΠΕΔΙΩΝ
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('cv_pdf_storage_key')
        batch_op.drop_column('cv_content_type')

    # ΑΦΑΙΡΕΣΕ Ή ΚΑΝΕ COMMENT OUT ΤΟ ΠΑΡΑΚΑΤΩ ΜΠΛΟΚ ΕΠΕΙΔΗ ΤΟ CONSTRAINT ΥΠΗΡΧΕ ΠΡΙΝ ΑΠΟ ΑΥΤΟ ΤΟ MIGRATION
    # with op.batch_alter_table('candidate_branch_association', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_candidate_branch', type_='unique')

    # ### end Alembic commands ###