"""Add offers JSONB field to Candidate and remove old offer fields

Revision ID: dca82aebca75
Revises: 819888491b73
Create Date: 2025-05-12 18:58:23.177630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dca82aebca75'
down_revision = '819888491b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('candidate_confirmation_status',
               existing_type=sa.VARCHAR(length=50),
               comment="Status of candidate's confirmation for the scheduled interview",
               existing_comment="Status of candidate's confirmation for the scheduled interview (Pending, Confirmed, Declined)",
               existing_nullable=True)
        batch_op.alter_column('confirmation_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique identifier for interview confirmation links',
               existing_comment='Unique identifier for interview confirmation links sent to candidate',
               existing_nullable=True)
        batch_op.drop_column('offer_response_date')
        batch_op.drop_column('offer_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('offer_response_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('confirmation_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='Unique identifier for interview confirmation links sent to candidate',
               existing_comment='Unique identifier for interview confirmation links',
               existing_nullable=True)
        batch_op.alter_column('candidate_confirmation_status',
               existing_type=sa.VARCHAR(length=50),
               comment="Status of candidate's confirmation for the scheduled interview (Pending, Confirmed, Declined)",
               existing_comment="Status of candidate's confirmation for the scheduled interview",
               existing_nullable=True)
        batch_op.drop_column('offers')

    # ### end Alembic commands ###
