"""Initial database schema

Revision ID: faa87c33089e
Revises: 
Create Date: 2025-05-12 11:25:11.819983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faa87c33089e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('cv_original_filename', sa.String(length=255), nullable=False),
    sa.Column('cv_storage_path', sa.String(length=512), nullable=False),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('work_experience', sa.Text(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=True),
    sa.Column('seminars', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interview_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_location', sa.String(length=255), nullable=True),
    sa.Column('evaluation_rating', sa.String(length=50), nullable=True),
    sa.Column('offer_details', sa.Text(), nullable=True),
    sa.Column('offer_response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('cv_storage_path')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_submission_date'), ['submission_date'], unique=False)

    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_position_name'), ['position_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('enable_interview_reminders', sa.Boolean(), nullable=False),
    sa.Column('reminder_lead_time_minutes', sa.Integer(), nullable=False),
    sa.Column('email_interview_reminders', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('candidate_position_association',
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'position_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate_position_association')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_position_name'))

    op.drop_table('positions')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_submission_date'))
        batch_op.drop_index(batch_op.f('ix_candidates_email'))
        batch_op.drop_index(batch_op.f('ix_candidates_current_status'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
