"""Integrate branches fully and calendar interview support

Revision ID: fe1c9a5e8ed0
Revises: 910b4da24188
Create Date: 2025-05-20 23:19:39.923803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1c9a5e8ed0'
down_revision = '910b4da24188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ο περιορισμός 'uq_candidate_branch' φαίνεται να υπάρχει ήδη,
    # οπότε σχολιάζουμε την προσπάθεια δημιουργίας του.
    # with op.batch_alter_table('candidate_branch_association', schema=None) as batch_op:
    #     batch_op.create_unique_constraint('uq_candidate_branch', ['candidate_id', 'branch_id'])
    pass # Προσθέτουμε pass αν δεν υπάρχουν άλλες εντολές στην upgrade

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Αντίστοιχα, σχολιάζουμε και την αφαίρεση του περιορισμού.
    # with op.batch_alter_table('candidate_branch_association', schema=None) as batch_op:
    #     batch_op.drop_constraint('uq_candidate_branch', type_='unique')
    pass # Προσθέτουμε pass αν δεν υπάρχουν άλλες εντολές στην downgrade

    # ### end Alembic commands ###