"""Add user registration confirmation and approval fields

Revision ID: ff1e22b0d9a0
Revises: dca82aebca75
Create Date: 2025-05-12 21:00:00.123456 # Η πραγματική ημερομηνία δημιουργίας σου θα είναι εδώ

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression # Εξασφάλισε ότι αυτό το import υπάρχει


# revision identifiers, used by Alembic.
revision = 'ff1e22b0d9a0'
down_revision = 'dca82aebca75' # Αυτό είναι το σωστό ID του προηγούμενου migration
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - αλλά τα προσαρμόζουμε ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=expression.false()))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=expression.false()))
        batch_op.add_column(sa.Column('is_approved_account', sa.Boolean(), nullable=False, server_default=expression.false()))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('is_approved_account')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###